### ISSUE TITLE
Implement LoopedRandomInstantiation analyzer

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/VSDiagnostics#4]
When a `Random` instance is created inside a loop then it should show a warning. In C#, this will cause the instance to return the same values since it doesn't guard for this on a lower level.

**Comment by Hosch250** [comment]
This could be difficult to tell efficiently because we have to recurse the tree checking the parents.  Is stopping as soon as we reach a method, ctor, or property node enough?  Any other nodes I should consider?  A simpler way would be to recurse until the node is null, but that is more inefficient.

**Comment by Vannevelj** [comment]
As soon as you reach those three (method/ctor/property) then that's good enough: the only levels above that are class and namespace. I believe these first 3 are the only ones that can have a body like that.

**Comment by Hosch250** [comment]
OK, thanks for the clarification.
